const express = require("express")
const EmployeeRoute = require('./Routes/EmployeeRoute')
const cors = require("cors")
require('dotenv').config()
const connectdb = require("./mongodb")
const app = express()
app.use(express.json())
app.use(cors())
connectdb()
app.use('/',EmployeeRoute)
app.listen(process.env.PORT, ()=>{console.log('Server is running on', `${process.env.PORT}`)})